-- Minced -- canonical ingredient vocabulary (M1.5.1)
--
-- Runs BEFORE supabase/seed.sql, which upserts the same 30 mockup ingredients
-- on top of this and then references them from its recipes.
--
-- IDEMPOTENT: every insert upserts on a natural key, so re-running converges on
-- this file's contents rather than duplicating.
--
-- NAMING RULE -- this is the whole quality argument, so it is written down:
--
--   canonical_name is what a COOK types. Aliases carry everything else,
--   including USDA FoodData Central's own phrasing.
--
--     canonical   red bell pepper
--     aliases     bell pepper, sweet red pepper, red peppers,
--                 "peppers, sweet, red"      <- USDA's spelling
--
--   USDA supplies the COVERAGE (what ingredients exist, at what breadth);
--   curation supplies the NAMES. Letting USDA's phrasing become canonical would
--   put "Onions, raw" in the pantry autocomplete. Keeping USDA spellings as
--   aliases also pre-wires the fdc_id mapping M1.5.4 needs.
--
-- SPLITTING RULE: a row earns its own canonical entry only when a cook would
-- shop for it separately AND swapping it changes the dish. "russet potato" and
-- "red potato" split; "extra-virgin olive oil" does not -- it is an alias of
-- olive oil. Over-splitting is the quiet killer here: a pantry holding "potato"
-- should not miss a recipe calling for "potatoes".

begin;

-- ---------------------------------------------------------------------------
-- Produce
-- ---------------------------------------------------------------------------
insert into ingredients (canonical_name, slug, aisle_category, is_pantry_staple) values
  ('yellow onion',        'yellow-onion',        'Produce', false),
  ('red onion',           'red-onion',           'Produce', false),
  ('white onion',         'white-onion',         'Produce', false),
  ('sweet onion',         'sweet-onion',         'Produce', false),
  ('shallot',             'shallot',             'Produce', false),
  ('scallion',            'scallion',            'Produce', false),
  ('garlic',              'garlic',              'Produce', false),
  ('leek',                'leek',                'Produce', false),
  ('chives',              'chives',              'Produce', false),
  ('carrot',              'carrot',              'Produce', false),
  ('celery',              'celery',              'Produce', false),
  ('russet potato',       'russet-potato',       'Produce', false),
  ('red potato',          'red-potato',          'Produce', false),
  ('yukon gold potato',   'yukon-gold-potato',   'Produce', false),
  ('sweet potato',        'sweet-potato',        'Produce', false),
  ('turnip',              'turnip',              'Produce', false),
  ('parsnip',             'parsnip',             'Produce', false),
  ('rutabaga',            'rutabaga',            'Produce', false),
  ('radish',              'radish',              'Produce', false),
  ('beet',                'beet',                'Produce', false),
  ('jicama',              'jicama',              'Produce', false),
  ('spinach',             'spinach',             'Produce', false),
  ('kale',                'kale',                'Produce', false),
  ('swiss chard',         'swiss-chard',         'Produce', false),
  ('collard greens',      'collard-greens',      'Produce', false),
  ('mustard greens',      'mustard-greens',      'Produce', false),
  ('arugula',             'arugula',             'Produce', false),
  ('romaine lettuce',     'romaine-lettuce',     'Produce', false),
  ('iceberg lettuce',     'iceberg-lettuce',     'Produce', false),
  ('butter lettuce',      'butter-lettuce',      'Produce', false),
  ('mixed greens',        'mixed-greens',        'Produce', false),
  ('watercress',          'watercress',          'Produce', false),
  ('bok choy',            'bok-choy',            'Produce', false),
  ('napa cabbage',        'napa-cabbage',        'Produce', false),
  ('green cabbage',       'green-cabbage',       'Produce', false),
  ('red cabbage',         'red-cabbage',         'Produce', false),
  ('brussels sprouts',    'brussels-sprouts',    'Produce', false),
  ('broccoli',            'broccoli',            'Produce', false),
  ('broccoli rabe',       'broccoli-rabe',       'Produce', false),
  ('cauliflower',         'cauliflower',         'Produce', false),
  ('red bell pepper',     'red-bell-pepper',     'Produce', false),
  ('green bell pepper',   'green-bell-pepper',   'Produce', false),
  ('yellow bell pepper',  'yellow-bell-pepper',  'Produce', false),
  ('jalapeno',            'jalapeno',            'Produce', false),
  ('serrano pepper',      'serrano-pepper',      'Produce', false),
  ('poblano pepper',      'poblano-pepper',      'Produce', false),
  ('habanero',            'habanero',            'Produce', false),
  ('anaheim chile',       'anaheim-chile',       'Produce', false),
  ('thai chile',          'thai-chile',          'Produce', false),
  ('tomato',              'tomato',              'Produce', false),
  ('cherry tomato',       'cherry-tomato',       'Produce', false),
  ('roma tomato',         'roma-tomato',         'Produce', false),
  ('tomatillo',           'tomatillo',           'Produce', false),
  ('cucumber',            'cucumber',            'Produce', false),
  ('zucchini',            'zucchini',            'Produce', false),
  ('yellow squash',       'yellow-squash',       'Produce', false),
  ('butternut squash',    'butternut-squash',    'Produce', false),
  ('acorn squash',        'acorn-squash',        'Produce', false),
  ('spaghetti squash',    'spaghetti-squash',    'Produce', false),
  ('pumpkin',             'pumpkin',             'Produce', false),
  ('eggplant',            'eggplant',            'Produce', false),
  ('okra',                'okra',                'Produce', false),
  ('green beans',         'green-beans',         'Produce', false),
  ('snap peas',           'snap-peas',           'Produce', false),
  ('snow peas',           'snow-peas',           'Produce', false),
  ('corn',                'corn',                'Produce', false),
  ('asparagus',           'asparagus',           'Produce', false),
  ('artichoke',           'artichoke',           'Produce', false),
  ('fennel',              'fennel',              'Produce', false),
  ('mushrooms',           'mushrooms',           'Produce', false),
  ('cremini mushrooms',   'cremini-mushrooms',   'Produce', false),
  ('shiitake mushrooms',  'shiitake-mushrooms',  'Produce', false),
  ('portobello mushrooms','portobello-mushrooms','Produce', false),
  ('oyster mushrooms',    'oyster-mushrooms',    'Produce', false),
  ('fresh parsley',      'fresh-parsley',      'Produce', false),
  ('fresh cilantro',     'fresh-cilantro',     'Produce', false),
  ('fresh basil',        'fresh-basil',        'Produce', false),
  ('fresh mint',         'fresh-mint',         'Produce', false),
  ('fresh dill',         'fresh-dill',         'Produce', false),
  ('fresh rosemary',     'fresh-rosemary',     'Produce', false),
  ('fresh thyme',        'fresh-thyme',        'Produce', false),
  ('fresh sage',         'fresh-sage',         'Produce', false),
  ('fresh oregano',      'fresh-oregano',      'Produce', false),
  ('fresh tarragon',     'fresh-tarragon',     'Produce', false),
  ('ginger',              'ginger',              'Produce', false),
  ('lemongrass',          'lemongrass',          'Produce', false),
  ('lemon',               'lemon',               'Produce', false),
  ('lime',                'lime',                'Produce', false),
  ('orange',              'orange',              'Produce', false),
  ('grapefruit',          'grapefruit',          'Produce', false),
  ('apple',               'apple',               'Produce', false),
  ('pear',                'pear',                'Produce', false),
  ('banana',              'banana',              'Produce', false),
  ('plantain',            'plantain',            'Produce', false),
  ('strawberries',        'strawberries',        'Produce', false),
  ('blueberries',         'blueberries',         'Produce', false),
  ('raspberries',         'raspberries',         'Produce', false),
  ('blackberries',        'blackberries',        'Produce', false),
  ('grapes',              'grapes',              'Produce', false),
  ('pineapple',           'pineapple',           'Produce', false),
  ('mango',               'mango',               'Produce', false),
  ('peach',               'peach',               'Produce', false),
  ('plum',                'plum',                'Produce', false),
  ('cherries',            'cherries',            'Produce', false),
  ('watermelon',          'watermelon',          'Produce', false),
  ('cantaloupe',          'cantaloupe',          'Produce', false),
  ('avocado',             'avocado',             'Produce', false),
  ('pomegranate',         'pomegranate',         'Produce', false),
  ('kiwi',                'kiwi',                'Produce', false)
on conflict (canonical_name) do update
  set aisle_category   = excluded.aisle_category,
      is_pantry_staple = excluded.is_pantry_staple;

-- ---------------------------------------------------------------------------
-- Pantry
--
-- The is_pantry_staple flags start here. CLAUDE.md: salt, pepper, water, oil,
-- butter, sugar and flour never count toward "you're missing". Forgetting one
-- makes every match report a miss and the product feel broken.
-- ---------------------------------------------------------------------------
insert into ingredients (canonical_name, slug, aisle_category, is_pantry_staple) values
  ('olive oil',            'olive-oil',            'Pantry', true),
  ('vegetable oil',        'vegetable-oil',        'Pantry', true),
  ('canola oil',           'canola-oil',           'Pantry', true),
  ('water',                'water',                'Pantry', true),
  ('granulated sugar',     'granulated-sugar',     'Pantry', true),
  ('all-purpose flour',    'all-purpose-flour',    'Pantry', true),
  ('coconut oil',          'coconut-oil',          'Pantry', false),
  ('toasted sesame oil',   'toasted-sesame-oil',   'Pantry', false),
  ('peanut oil',           'peanut-oil',           'Pantry', false),
  ('avocado oil',          'avocado-oil',          'Pantry', false),
  ('cooking spray',        'cooking-spray',        'Pantry', true),
  ('white vinegar',        'white-vinegar',        'Pantry', true),
  ('apple cider vinegar',  'apple-cider-vinegar',  'Pantry', false),
  ('red wine vinegar',     'red-wine-vinegar',     'Pantry', false),
  ('white wine vinegar',   'white-wine-vinegar',   'Pantry', false),
  ('rice vinegar',         'rice-vinegar',         'Pantry', false),
  ('balsamic vinegar',     'balsamic-vinegar',     'Pantry', false),
  ('sherry vinegar',       'sherry-vinegar',       'Pantry', false),
  ('crushed tomatoes',     'crushed-tomatoes',     'Pantry', false),
  ('whole tomatoes',       'whole-tomatoes',       'Pantry', false),
  ('diced tomatoes',       'diced-tomatoes',       'Pantry', false),
  ('tomato paste',         'tomato-paste',         'Pantry', false),
  ('tomato sauce',         'tomato-sauce',         'Pantry', false),
  ('sun-dried tomatoes',   'sun-dried-tomatoes',   'Pantry', false),
  ('roasted red peppers',  'roasted-red-peppers',  'Pantry', false),
  ('coconut milk',         'coconut-milk',         'Pantry', false),
  ('chicken broth',        'chicken-broth',        'Pantry', false),
  ('beef broth',           'beef-broth',           'Pantry', false),
  ('vegetable broth',      'vegetable-broth',      'Pantry', false),
  ('evaporated milk',      'evaporated-milk',      'Pantry', false),
  ('sweetened condensed milk','sweetened-condensed-milk','Pantry', false),
  ('chickpeas',            'chickpeas',            'Pantry', false),
  ('black beans',          'black-beans',          'Pantry', false),
  ('kidney beans',         'kidney-beans',         'Pantry', false),
  ('pinto beans',          'pinto-beans',          'Pantry', false),
  ('cannellini beans',     'cannellini-beans',     'Pantry', false),
  ('navy beans',           'navy-beans',           'Pantry', false),
  ('great northern beans', 'great-northern-beans', 'Pantry', false),
  ('black-eyed peas',      'black-eyed-peas',      'Pantry', false),
  ('refried beans',        'refried-beans',        'Pantry', false),
  ('lentils',              'lentils',              'Pantry', false),
  ('red lentils',          'red-lentils',          'Pantry', false),
  ('split peas',           'split-peas',           'Pantry', false),
  ('white rice',           'white-rice',           'Pantry', false),
  ('brown rice',           'brown-rice',           'Pantry', false),
  ('jasmine rice',         'jasmine-rice',         'Pantry', false),
  ('basmati rice',         'basmati-rice',         'Pantry', false),
  ('arborio rice',         'arborio-rice',         'Pantry', false),
  ('wild rice',            'wild-rice',            'Pantry', false),
  ('quinoa',               'quinoa',               'Pantry', false),
  ('couscous',             'couscous',             'Pantry', false),
  ('bulgur',               'bulgur',               'Pantry', false),
  ('farro',                'farro',                'Pantry', false),
  ('barley',               'barley',               'Pantry', false),
  ('rolled oats',          'rolled-oats',          'Pantry', false),
  ('steel-cut oats',       'steel-cut-oats',       'Pantry', false),
  ('cornmeal',             'cornmeal',             'Pantry', false),
  ('polenta',              'polenta',              'Pantry', false),
  ('grits',                'grits',                'Pantry', false),
  ('spaghetti',            'spaghetti',            'Pantry', false),
  ('penne',                'penne',                'Pantry', false),
  ('rigatoni',             'rigatoni',             'Pantry', false),
  ('fusilli',              'fusilli',              'Pantry', false),
  ('macaroni',             'macaroni',             'Pantry', false),
  ('lasagna noodles',      'lasagna-noodles',      'Pantry', false),
  ('egg noodles',          'egg-noodles',          'Pantry', false),
  ('orzo',                 'orzo',                 'Pantry', false),
  ('linguine',             'linguine',             'Pantry', false),
  ('fettuccine',           'fettuccine',           'Pantry', false),
  ('angel hair',           'angel-hair',           'Pantry', false),
  ('ramen noodles',        'ramen-noodles',        'Pantry', false),
  ('rice noodles',         'rice-noodles',         'Pantry', false),
  ('soba noodles',         'soba-noodles',         'Pantry', false),
  ('udon noodles',         'udon-noodles',         'Pantry', false),
  ('whole wheat flour',    'whole-wheat-flour',    'Pantry', false),
  ('bread flour',          'bread-flour',          'Pantry', false),
  ('cornstarch',           'cornstarch',           'Pantry', false),
  ('baking powder',        'baking-powder',        'Pantry', true),
  ('baking soda',          'baking-soda',          'Pantry', true),
  ('active dry yeast',     'active-dry-yeast',     'Pantry', false),
  ('brown sugar',          'brown-sugar',          'Pantry', false),
  ('powdered sugar',       'powdered-sugar',       'Pantry', false),
  ('honey',                'honey',                'Pantry', false),
  ('maple syrup',          'maple-syrup',          'Pantry', false),
  ('molasses',             'molasses',             'Pantry', false),
  ('vanilla extract',      'vanilla-extract',      'Pantry', true),
  ('cocoa powder',         'cocoa-powder',         'Pantry', false),
  ('chocolate chips',      'chocolate-chips',      'Pantry', false),
  ('semisweet chocolate',  'semisweet-chocolate',  'Pantry', false),
  ('breadcrumbs',          'breadcrumbs',          'Pantry', false),
  ('panko breadcrumbs',    'panko-breadcrumbs',    'Pantry', false),
  ('soy sauce',            'soy-sauce',            'Pantry', false),
  ('tamari',               'tamari',               'Pantry', false),
  ('fish sauce',           'fish-sauce',           'Pantry', false),
  ('oyster sauce',         'oyster-sauce',         'Pantry', false),
  ('hoisin sauce',         'hoisin-sauce',         'Pantry', false),
  ('worcestershire sauce', 'worcestershire-sauce', 'Pantry', false),
  ('sriracha',             'sriracha',             'Pantry', false),
  ('hot sauce',            'hot-sauce',            'Pantry', false),
  ('gochujang',            'gochujang',            'Pantry', false),
  ('harissa paste',        'harissa-paste',        'Pantry', false),
  ('white miso',           'white-miso',           'Pantry', false),
  ('tahini',               'tahini',               'Pantry', false),
  ('peanut butter',        'peanut-butter',        'Pantry', false),
  ('almond butter',        'almond-butter',        'Pantry', false),
  ('mayonnaise',           'mayonnaise',           'Pantry', false),
  ('ketchup',              'ketchup',              'Pantry', false),
  ('yellow mustard',       'yellow-mustard',       'Pantry', false),
  ('dijon mustard',        'dijon-mustard',        'Pantry', false),
  ('whole grain mustard',  'whole-grain-mustard',  'Pantry', false),
  ('barbecue sauce',       'barbecue-sauce',       'Pantry', false),
  ('salsa',                'salsa',                'Pantry', false),
  ('pesto',                'pesto',                'Pantry', false),
  ('red curry paste',      'red-curry-paste',      'Pantry', false),
  ('green curry paste',    'green-curry-paste',    'Pantry', false),
  ('almonds',              'almonds',              'Pantry', false),
  ('walnuts',              'walnuts',              'Pantry', false),
  ('pecans',               'pecans',               'Pantry', false),
  ('cashews',              'cashews',              'Pantry', false),
  ('pistachios',           'pistachios',           'Pantry', false),
  ('peanuts',              'peanuts',              'Pantry', false),
  ('pine nuts',            'pine-nuts',            'Pantry', false),
  ('hazelnuts',            'hazelnuts',            'Pantry', false),
  ('sunflower seeds',      'sunflower-seeds',      'Pantry', false),
  ('pumpkin seeds',        'pumpkin-seeds',        'Pantry', false),
  ('sesame seeds',         'sesame-seeds',         'Pantry', false),
  ('chia seeds',           'chia-seeds',           'Pantry', false),
  ('flaxseed',             'flaxseed',             'Pantry', false),
  ('raisins',              'raisins',              'Pantry', false),
  ('dried cranberries',    'dried-cranberries',    'Pantry', false),
  ('dates',                'dates',                'Pantry', false),
  ('shredded coconut',     'shredded-coconut',     'Pantry', false),
  ('capers',               'capers',               'Pantry', false),
  ('kalamata olives',      'kalamata-olives',      'Pantry', false),
  ('green olives',         'green-olives',         'Pantry', false),
  ('pickles',              'pickles',              'Pantry', false),
  ('sauerkraut',           'sauerkraut',           'Pantry', false),
  ('kimchi',               'kimchi',               'Pantry', false),
  ('nori',                 'nori',                 'Pantry', false),
  ('dry white wine',       'dry-white-wine',       'Pantry', false),
  ('dry red wine',         'dry-red-wine',         'Pantry', false),
  ('mirin',                'mirin',                'Pantry', false),
  ('sake',                 'sake',                 'Pantry', false)
on conflict (canonical_name) do update
  set aisle_category   = excluded.aisle_category,
      is_pantry_staple = excluded.is_pantry_staple;

-- ---------------------------------------------------------------------------
-- Dairy
--
-- Plant milks live here too: they sit in the dairy aisle and substitute for the
-- same line in a recipe, which is what aisle_category is for.
-- ---------------------------------------------------------------------------
insert into ingredients (canonical_name, slug, aisle_category, is_pantry_staple) values
  ('butter',            'butter',            'Dairy', true),
  ('unsalted butter',   'unsalted-butter',   'Dairy', true),
  ('milk',              'milk',              'Dairy', false),
  ('buttermilk',        'buttermilk',        'Dairy', false),
  ('heavy cream',       'heavy-cream',       'Dairy', false),
  ('half-and-half',     'half-and-half',     'Dairy', false),
  ('sour cream',        'sour-cream',        'Dairy', false),
  ('plain yogurt',      'plain-yogurt',      'Dairy', false),
  ('greek yogurt',      'greek-yogurt',      'Dairy', false),
  ('cream cheese',      'cream-cheese',      'Dairy', false),
  ('ghee',              'ghee',              'Dairy', false),
  ('cheddar cheese',    'cheddar-cheese',    'Dairy', false),
  ('mozzarella',        'mozzarella',        'Dairy', false),
  ('fresh mozzarella',  'fresh-mozzarella',  'Dairy', false),
  ('parmesan',          'parmesan',          'Dairy', false),
  ('pecorino romano',   'pecorino-romano',   'Dairy', false),
  ('feta',              'feta',              'Dairy', false),
  ('goat cheese',       'goat-cheese',       'Dairy', false),
  ('ricotta',           'ricotta',           'Dairy', false),
  ('cottage cheese',    'cottage-cheese',    'Dairy', false),
  ('monterey jack',     'monterey-jack',     'Dairy', false),
  ('pepper jack',       'pepper-jack',       'Dairy', false),
  ('swiss cheese',      'swiss-cheese',      'Dairy', false),
  ('provolone',         'provolone',         'Dairy', false),
  ('gruyere',           'gruyere',           'Dairy', false),
  ('blue cheese',       'blue-cheese',       'Dairy', false),
  ('queso fresco',      'queso-fresco',      'Dairy', false),
  ('cotija',            'cotija',            'Dairy', false),
  ('mascarpone',        'mascarpone',        'Dairy', false),
  ('halloumi',          'halloumi',          'Dairy', false),
  ('american cheese',   'american-cheese',   'Dairy', false),
  ('almond milk',       'almond-milk',       'Dairy', false),
  ('soy milk',          'soy-milk',          'Dairy', false),
  ('oat milk',          'oat-milk',          'Dairy', false)
on conflict (canonical_name) do update
  set aisle_category   = excluded.aisle_category,
      is_pantry_staple = excluded.is_pantry_staple;

-- ---------------------------------------------------------------------------
-- Protein
-- ---------------------------------------------------------------------------
insert into ingredients (canonical_name, slug, aisle_category, is_pantry_staple) values
  ('chicken breast',    'chicken-breast',    'Protein', false),
  ('chicken thighs',    'chicken-thighs',    'Protein', false),
  ('chicken drumsticks','chicken-drumsticks','Protein', false),
  ('chicken wings',     'chicken-wings',     'Protein', false),
  ('whole chicken',     'whole-chicken',     'Protein', false),
  ('ground chicken',    'ground-chicken',    'Protein', false),
  ('rotisserie chicken','rotisserie-chicken','Protein', false),
  ('ground beef',       'ground-beef',       'Protein', false),
  ('chuck roast',       'chuck-roast',       'Protein', false),
  ('beef stew meat',    'beef-stew-meat',    'Protein', false),
  ('sirloin steak',     'sirloin-steak',     'Protein', false),
  ('ribeye',            'ribeye',            'Protein', false),
  ('flank steak',       'flank-steak',       'Protein', false),
  ('skirt steak',       'skirt-steak',       'Protein', false),
  ('brisket',           'brisket',           'Protein', false),
  ('short ribs',        'short-ribs',        'Protein', false),
  ('pork chops',        'pork-chops',        'Protein', false),
  ('pork tenderloin',   'pork-tenderloin',   'Protein', false),
  ('pork shoulder',     'pork-shoulder',     'Protein', false),
  ('ground pork',       'ground-pork',       'Protein', false),
  ('bacon',             'bacon',             'Protein', false),
  ('pancetta',          'pancetta',          'Protein', false),
  ('prosciutto',        'prosciutto',        'Protein', false),
  ('ham',               'ham',               'Protein', false),
  ('italian sausage',   'italian-sausage',   'Protein', false),
  ('breakfast sausage', 'breakfast-sausage', 'Protein', false),
  ('chorizo',           'chorizo',           'Protein', false),
  ('hot dogs',          'hot-dogs',          'Protein', false),
  ('ground turkey',     'ground-turkey',     'Protein', false),
  ('turkey breast',     'turkey-breast',     'Protein', false),
  ('ground lamb',       'ground-lamb',       'Protein', false),
  ('lamb shoulder',     'lamb-shoulder',     'Protein', false),
  ('lamb chops',        'lamb-chops',        'Protein', false),
  ('salmon',            'salmon',            'Protein', false),
  ('smoked salmon',     'smoked-salmon',     'Protein', false),
  ('tuna steak',        'tuna-steak',        'Protein', false),
  ('canned tuna',       'canned-tuna',       'Protein', false),
  ('cod',               'cod',               'Protein', false),
  ('tilapia',           'tilapia',           'Protein', false),
  ('halibut',           'halibut',           'Protein', false),
  ('trout',             'trout',             'Protein', false),
  ('snapper',           'snapper',           'Protein', false),
  ('shrimp',            'shrimp',            'Protein', false),
  ('scallops',          'scallops',          'Protein', false),
  ('mussels',           'mussels',           'Protein', false),
  ('clams',             'clams',             'Protein', false),
  ('crab',              'crab',              'Protein', false),
  ('lobster',           'lobster',           'Protein', false),
  ('squid',             'squid',             'Protein', false),
  ('anchovies',         'anchovies',         'Protein', false),
  ('sardines',          'sardines',          'Protein', false),
  ('egg',               'egg',               'Protein', false),
  ('egg whites',        'egg-whites',        'Protein', false),
  ('firm tofu',         'firm-tofu',         'Protein', false),
  ('silken tofu',       'silken-tofu',       'Protein', false),
  ('tempeh',            'tempeh',            'Protein', false),
  ('seitan',            'seitan',            'Protein', false),
  ('edamame',           'edamame',           'Protein', false)
on conflict (canonical_name) do update
  set aisle_category   = excluded.aisle_category,
      is_pantry_staple = excluded.is_pantry_staple;

-- ---------------------------------------------------------------------------
-- Spices
--
-- FRESH VS DRIED -- a curation decision worth stating, because it silently
-- decides thousands of matches later:
--
--   Herbs that a cook buys in both forms get the form IN the canonical name
--   ("fresh thyme" in Produce, "dried thyme" here). The bare word is then an
--   alias pointing at whichever form a recipe writing it bare almost always
--   means: fresh for the soft herbs sold in bunches (parsley, cilantro, basil,
--   mint, dill, tarragon), dried for the woody ones a pantry keeps in a jar
--   (oregano, thyme, rosemary, sage).
--
--   The alternative -- one row per herb -- means a pantry holding dried thyme
--   matches a recipe wanting fresh, and the user is told to use a jar of dust
--   where the dish needs a sprig. Splitting costs a few rows; not splitting
--   costs correctness.
-- ---------------------------------------------------------------------------
insert into ingredients (canonical_name, slug, aisle_category, is_pantry_staple) values
  ('salt',                  'salt',                  'Spices', true),
  ('kosher salt',           'kosher-salt',           'Spices', true),
  ('black pepper',          'black-pepper',          'Spices', true),
  ('white pepper',          'white-pepper',          'Spices', false),
  ('garlic powder',         'garlic-powder',         'Spices', true),
  ('onion powder',          'onion-powder',          'Spices', true),
  ('paprika',               'paprika',               'Spices', false),
  ('smoked paprika',        'smoked-paprika',        'Spices', false),
  ('chili powder',          'chili-powder',          'Spices', false),
  ('cayenne',               'cayenne',               'Spices', false),
  ('crushed red pepper',    'crushed-red-pepper',    'Spices', false),
  ('ground cumin',          'ground-cumin',          'Spices', false),
  ('ground coriander',      'ground-coriander',      'Spices', false),
  ('ground turmeric',       'ground-turmeric',       'Spices', false),
  ('ground ginger',         'ground-ginger',         'Spices', false),
  ('ground cinnamon',       'ground-cinnamon',       'Spices', true),
  ('cinnamon stick',        'cinnamon-stick',        'Spices', false),
  ('ground nutmeg',         'ground-nutmeg',         'Spices', false),
  ('ground allspice',       'ground-allspice',       'Spices', false),
  ('ground cloves',         'ground-cloves',         'Spices', false),
  ('cardamom',              'cardamom',              'Spices', false),
  ('star anise',            'star-anise',            'Spices', false),
  ('fennel seeds',          'fennel-seeds',          'Spices', false),
  ('mustard seeds',         'mustard-seeds',         'Spices', false),
  ('celery seed',           'celery-seed',           'Spices', false),
  ('caraway seeds',         'caraway-seeds',         'Spices', false),
  ('bay leaf',              'bay-leaf',              'Spices', false),
  ('dried oregano',         'dried-oregano',         'Spices', true),
  ('dried basil',           'dried-basil',           'Spices', false),
  ('dried thyme',           'dried-thyme',           'Spices', false),
  ('dried rosemary',        'dried-rosemary',        'Spices', false),
  ('dried sage',            'dried-sage',            'Spices', false),
  ('dried dill',            'dried-dill',            'Spices', false),
  ('dried parsley',         'dried-parsley',         'Spices', false),
  ('italian seasoning',     'italian-seasoning',     'Spices', false),
  ('herbes de provence',    'herbes-de-provence',    'Spices', false),
  ('poultry seasoning',     'poultry-seasoning',     'Spices', false),
  ('old bay seasoning',     'old-bay-seasoning',     'Spices', false),
  ('taco seasoning',        'taco-seasoning',        'Spices', false),
  ('curry powder',          'curry-powder',          'Spices', false),
  ('garam masala',          'garam-masala',          'Spices', false),
  ('chinese five spice',    'chinese-five-spice',    'Spices', false),
  ('za''atar',              'zaatar',                'Spices', false),
  ('sumac',                 'sumac',                 'Spices', false),
  ('saffron',               'saffron',               'Spices', false),
  ('everything bagel seasoning','everything-bagel-seasoning','Spices', false),
  ('furikake',              'furikake',              'Spices', false)
on conflict (canonical_name) do update
  set aisle_category   = excluded.aisle_category,
      is_pantry_staple = excluded.is_pantry_staple;

-- ---------------------------------------------------------------------------
-- Other -- breads, wrappers and doughs. Not produce, not shelf-stable pantry.
-- ---------------------------------------------------------------------------
insert into ingredients (canonical_name, slug, aisle_category, is_pantry_staple) values
  ('corn tortillas',    'corn-tortillas',    'Other', false),
  ('flour tortillas',   'flour-tortillas',   'Other', false),
  ('sandwich bread',    'sandwich-bread',    'Other', false),
  ('baguette',          'baguette',          'Other', false),
  ('sourdough bread',   'sourdough-bread',   'Other', false),
  ('pita bread',        'pita-bread',        'Other', false),
  ('naan',              'naan',              'Other', false),
  ('hamburger buns',    'hamburger-buns',    'Other', false),
  ('hot dog buns',      'hot-dog-buns',      'Other', false),
  ('english muffin',    'english-muffin',    'Other', false),
  ('bagel',             'bagel',             'Other', false),
  ('pizza dough',       'pizza-dough',       'Other', false),
  ('puff pastry',       'puff-pastry',       'Other', false),
  ('phyllo dough',      'phyllo-dough',      'Other', false),
  ('pie crust',         'pie-crust',         'Other', false),
  ('wonton wrappers',   'wonton-wrappers',   'Other', false),
  ('rice paper',        'rice-paper',        'Other', false),
  ('croutons',          'croutons',          'Other', false)
on conflict (canonical_name) do update
  set aisle_category   = excluded.aisle_category,
      is_pantry_staple = excluded.is_pantry_staple;

-- ---------------------------------------------------------------------------
-- Modifier vocabulary (M1.5.3)
--
-- Words stripped from an ingredient name ONLY when it fails to resolve outright.
-- Derived from the actual USDA MyPlate rejection queue, not invented.
--
-- THE RULE FOR ADDING ONE: a word belongs here only if removing it never
-- changes what you would put in the basket. "canned" stays (canned corn is
-- corn); "ground" does NOT (ground beef is not beef); "sweet" does NOT (a sweet
-- potato is not a potato). When unsure, leave it out -- an unresolved name gets
-- flagged, a wrongly stripped one gets silently imported.
-- ---------------------------------------------------------------------------
insert into ingredient_modifiers (word, position) values
  -- state and preparation
  ('fresh','leading'), ('frozen','leading'), ('canned','leading'),
  ('raw','leading'), ('cooked','leading'), ('uncooked','leading'),
  ('dried','leading'), ('stewed','leading'), ('instant','leading'),
  ('quick','leading'), ('cooking','leading'), ('prepared','leading'),
  ('drained','leading'), ('rinsed','leading'), ('packed','leading'),
  ('peeled','leading'), ('pitted','leading'), ('seedless','leading'),
  ('chopped','leading'), ('diced','leading'), ('sliced','leading'),
  ('shredded','leading'), ('grated','leading'), ('crumbled','leading'),
  ('crushed','leading'), ('cubed','leading'), ('halved','leading'),
  ('minced','leading'), ('cut','leading'), ('torn','leading'),
  -- size and grade
  ('large','leading'), ('medium','leading'), ('small','leading'),
  ('baby','leading'), ('mini','leading'), ('jumbo','leading'),
  ('extra','leading'), ('ripe','leading'), ('lean','leading'),
  ('boneless','leading'), ('skinless','leading'),
  -- the nutrition-label vocabulary: this is most of the MyPlate corpus
  ('low','leading'), ('lower','leading'), ('reduced','leading'),
  ('no','leading'), ('non','leading'), ('nonfat','leading'),
  ('free','leading'), ('lite','leading'), ('unsalted','leading'),
  ('unsweetened','leading'), ('unseasoned','leading'),
  ('salt','leading'), ('sodium','leading'), ('added','leading'),
  ('calorie','leading'), ('sugar','leading'), ('light','leading'),
  -- Colours. These look reckless -- "red onion" and "green beans" and "white
  -- rice" are all real, distinct ingredients -- but they are safe for the same
  -- reason everything here is safe: stripping runs LAST. Every one of those
  -- names matches its own row on the exact pass and never reaches the stripper.
  -- Only an unrecognised "red apples" gets its adjective removed.
  ('red','leading'), ('green','leading'), ('yellow','leading'),
  ('white','leading'), ('golden','leading'), ('purple','leading'),
  -- forms a food is sold in, which never change what the food IS
  ('fillets','trailing'),  ('fillet','trailing'),  ('filets','trailing'),
  ('kernels','trailing'),  ('chunks','trailing'),  ('cubes','trailing'),
  ('pieces','trailing'),   ('halves','trailing'),  ('slices','trailing'),
  ('strips','trailing'),   ('wedges','trailing'),  ('spears','trailing'),
  ('florets','trailing'),  ('leaves','trailing')
on conflict (word) do update set position = excluded.position;

-- ---------------------------------------------------------------------------
-- American pantry vocabulary (M1.5.3)
--
-- Every row below appeared in the USDA MyPlate unresolved queue. The catalog is
-- federal nutrition-program cooking: budget, family-sized, and shelf-stable, so
-- it needs margarine and bouillon in a way the design mockup's six recipes did
-- not.
-- ---------------------------------------------------------------------------
insert into ingredients (canonical_name, slug, aisle_category, is_pantry_staple) values
  ('margarine',            'margarine',            'Dairy',   true),
  ('shortening',           'shortening',           'Pantry',  false),
  ('applesauce',           'applesauce',           'Pantry',  false),
  ('apricot jam',          'apricot-jam',          'Pantry',  false),
  ('grape jelly',          'grape-jelly',          'Pantry',  false),
  ('strawberry jam',       'strawberry-jam',       'Pantry',  false),
  ('chicken bouillon',     'chicken-bouillon',     'Pantry',  false),
  ('beef bouillon',        'beef-bouillon',        'Pantry',  false),
  ('cream of tartar',      'cream-of-tartar',      'Pantry',  false),
  ('hominy',               'hominy',               'Pantry',  false),
  ('marshmallows',         'marshmallows',         'Pantry',  false),
  ('pancake mix',          'pancake-mix',          'Pantry',  false),
  ('biscuit mix',          'biscuit-mix',          'Pantry',  false),
  ('cake mix',             'cake-mix',             'Pantry',  false),
  ('pudding mix',          'pudding-mix',          'Pantry',  false),
  ('whipped topping',      'whipped-topping',      'Dairy',   false),
  ('pizza sauce',          'pizza-sauce',          'Pantry',  false),
  ('chili sauce',          'chili-sauce',          'Pantry',  false),
  ('cream of mushroom soup','cream-of-mushroom-soup','Pantry', false),
  ('cream of chicken soup','cream-of-chicken-soup','Pantry',  false),
  ('tomato soup',          'tomato-soup',          'Pantry',  false),
  ('salad dressing',       'salad-dressing',       'Pantry',  false),
  ('italian dressing',     'italian-dressing',     'Pantry',  false),
  ('ranch dressing',       'ranch-dressing',       'Pantry',  false),
  ('vinaigrette',          'vinaigrette',          'Pantry',  false),
  ('mixed vegetables',     'mixed-vegetables',     'Produce', false),
  ('green chiles',         'green-chiles',         'Pantry',  false),
  ('papaya',               'papaya',               'Produce', false),
  ('mandarin orange',      'mandarin-orange',      'Produce', false),
  ('frozen yogurt',        'frozen-yogurt',        'Dairy',   false),
  ('vanilla yogurt',       'vanilla-yogurt',       'Dairy',   false),
  ('evaporated skim milk', 'evaporated-skim-milk', 'Pantry',  false),
  ('dry milk powder',      'dry-milk-powder',      'Pantry',  false),
  ('vegetable juice',      'vegetable-juice',      'Pantry',  false),
  ('apple juice',          'apple-juice',          'Pantry',  false),
  ('orange juice',         'orange-juice',         'Pantry',  false),
  ('cranberry juice',      'cranberry-juice',      'Pantry',  false),
  ('grape juice',          'grape-juice',          'Pantry',  false),
  ('raisin bran',          'raisin-bran',          'Pantry',  false),
  ('corn flakes',          'corn-flakes',          'Pantry',  false),
  ('graham crackers',      'graham-crackers',      'Pantry',  false),
  ('saltine crackers',     'saltine-crackers',     'Pantry',  false),
  ('tortilla chips',       'tortilla-chips',       'Pantry',  false),
  ('seasoned breadcrumbs', 'seasoned-breadcrumbs', 'Pantry',  false),
  ('cornbread mix',        'cornbread-mix',        'Pantry',  false),
  ('sweet pickle relish',  'sweet-pickle-relish',  'Pantry',  false),
  ('taco shells',          'taco-shells',          'Other',   false),
  ('hamburger',            'hamburger',            'Protein', false),
  ('turkey ham',           'turkey-ham',           'Protein', false),
  ('imitation crab',       'imitation-crab',       'Protein', false),
  ('peanut butter chips',  'peanut-butter-chips',  'Pantry',  false),
  ('butternut squash puree','butternut-squash-puree','Pantry',false),
  ('pumpkin puree',        'pumpkin-puree',        'Pantry',  false),
  ('egg substitute',       'egg-substitute',       'Protein', false),
  ('peas',                 'peas',                 'Produce', false),
  ('dried apricots',       'dried-apricots',       'Pantry',  false),
  ('prunes',               'prunes',               'Pantry',  false),
  ('ham hocks',            'ham-hocks',            'Protein', false),
  ('deli ham',             'deli-ham',             'Protein', false),
  ('deli turkey',          'deli-turkey',          'Protein', false),
  ('cream-style corn',     'cream-style-corn',     'Pantry',  false),
  ('coffee',               'coffee',               'Pantry',  false),
  ('popcorn',              'popcorn',              'Pantry',  false),
  ('granola',              'granola',              'Pantry',  false),
  ('baking mix',           'baking-mix',           'Pantry',  false),
  ('apple pie spice',      'apple-pie-spice',      'Spices',  false),
  ('pumpkin pie spice',    'pumpkin-pie-spice',    'Spices',  false),
  ('adobo seasoning',      'adobo-seasoning',      'Spices',  false),
  ('lemon pepper',         'lemon-pepper',         'Spices',  false),
  ('seasoning mix',        'seasoning-mix',        'Spices',  false),
  ('fruit juice',          'fruit-juice',          'Pantry',  false),
  ('fruit cocktail',       'fruit-cocktail',       'Pantry',  false),
  ('canned peaches',       'canned-peaches',       'Pantry',  false),
  ('canned pears',         'canned-pears',         'Pantry',  false),
  ('bread dough',          'bread-dough',          'Other',   false),
  ('italian bread',        'italian-bread',        'Other',   false),
  ('crescent rolls',       'crescent-rolls',       'Other',   false),
  ('dinner rolls',         'dinner-rolls',         'Other',   false),
  -- Second pass, chosen by frequency from the full 1,119-recipe rejection
  -- queue rather than guessed. "pasta" alone blocked 14 recipes: the catalog
  -- had spaghetti and penne and macaroni but no word for pasta in general.
  ('pasta',                'pasta',                'Pantry',  false),
  ('chicken',              'chicken',              'Protein', false),
  ('white beans',          'white-beans',          'Pantry',  false),
  ('lima beans',           'lima-beans',           'Pantry',  false),
  ('tomato juice',         'tomato-juice',         'Pantry',  false),
  ('marinara sauce',       'marinara-sauce',       'Pantry',  false),
  ('taco sauce',           'taco-sauce',           'Pantry',  false),
  ('matzo meal',           'matzo-meal',           'Pantry',  false),
  ('cereal',               'cereal',               'Pantry',  false),
  ('bran cereal',          'bran-cereal',          'Pantry',  false),
  ('pretzels',             'pretzels',             'Pantry',  false),
  ('water chestnuts',      'water-chestnuts',      'Pantry',  false),
  ('poppy seeds',          'poppy-seeds',          'Spices',  false),
  ('dried fruit',          'dried-fruit',          'Pantry',  false),
  ('dried figs',           'dried-figs',           'Pantry',  false),
  ('figs',                 'figs',                 'Produce', false),
  ('summer squash',        'summer-squash',        'Produce', false),
  ('winter squash',        'winter-squash',        'Produce', false),
  ('chili peppers',        'chili-peppers',        'Produce', false),
  ('strawberry yogurt',    'strawberry-yogurt',    'Dairy',   false),
  ('shredded cheese',      'shredded-cheese',      'Dairy',   false),
  ('walleye',              'walleye',              'Protein', false),
  ('catfish',              'catfish',              'Protein', false),
  ('pollock',              'pollock',              'Protein', false),
  ('spaghetti sauce',      'spaghetti-sauce',      'Pantry',  false)
on conflict (canonical_name) do update
  set aisle_category   = excluded.aisle_category,
      is_pantry_staple = excluded.is_pantry_staple;

-- ---------------------------------------------------------------------------
-- World-cuisine vocabulary (wave 1, content lane)
--
-- The USDA catalog is American home cooking, so the vocabulary had almost no
-- Korean, South and Southeast Asian, Ethiopian, Caribbean, Peruvian, Chinese or
-- Japanese staples. Each row below is something a cook in those traditions
-- shops for BY NAME and cannot swap without changing the dish -- the splitting
-- rule at the top of this file. Examples of the judgement calls:
--
--   gochugaru vs crushed red pepper   different flakes, different dish
--   scotch bonnet vs habanero         close, but a Caribbean cook buys one
--   tamarind paste                    the souring agent of a dozen cuisines
--   dried red chiles vs chile de arbol  whole Asian dried chiles vs the Mexican
--                                     one named in the recipe
--   green vs ripe plantain            tostones and kelewele are different foods
--   toor / chana / urad dal           three lentils, three jobs; none substitute
--
-- Names are what a COOK types; romanisations and regional names are aliases.
-- ---------------------------------------------------------------------------
insert into ingredients (canonical_name, slug, aisle_category, is_pantry_staple) values
  -- Produce
  ('daikon',                       'daikon',                       'Produce', false),
  ('bean sprouts',                 'bean-sprouts',                 'Produce', false),
  ('soybean sprouts',              'soybean-sprouts',              'Produce', false),
  ('curry leaves',                 'curry-leaves',                 'Produce', false),
  ('galangal',                     'galangal',                     'Produce', false),
  ('kaffir lime leaves',           'kaffir-lime-leaves',           'Produce', false),
  ('thai basil',                   'thai-basil',                   'Produce', false),
  ('holy basil',                   'holy-basil',                   'Produce', false),
  ('green papaya',                 'green-papaya',                 'Produce', false),
  ('long beans',                   'long-beans',                   'Produce', false),
  ('thai eggplant',                'thai-eggplant',                'Produce', false),
  ('water spinach',                'water-spinach',                'Produce', false),
  ('scotch bonnet',                'scotch-bonnet',                'Produce', false),
  ('green plantain',               'green-plantain',               'Produce', false),
  ('ripe plantain',                'ripe-plantain',                'Produce', false),
  -- Dairy
  ('paneer',                       'paneer',                       'Dairy',   false),
  ('mexican crema',                'mexican-crema',                'Dairy',   false),
  -- Protein
  ('pork belly',                   'pork-belly',                   'Protein', false),
  ('fish cakes',                   'fish-cakes',                   'Protein', false),
  ('dried shrimp',                 'dried-shrimp',                 'Protein', false),
  ('liver pate',                   'liver-pate',                   'Protein', false),
  -- Pantry: sauces, pastes, vinegars, wines
  ('dashi',                        'dashi',                        'Pantry',  false),
  ('bonito flakes',                'bonito-flakes',                'Pantry',  false),
  ('kombu',                        'kombu',                        'Pantry',  false),
  ('wakame',                       'wakame',                       'Pantry',  false),
  ('aonori',                       'aonori',                       'Pantry',  false),
  ('okonomiyaki sauce',            'okonomiyaki-sauce',            'Pantry',  false),
  ('pickled ginger',               'pickled-ginger',               'Pantry',  false),
  ('japanese curry roux',          'japanese-curry-roux',          'Pantry',  false),
  ('black vinegar',                'black-vinegar',                'Pantry',  false),
  ('cane vinegar',                 'cane-vinegar',                 'Pantry',  false),
  ('shaoxing wine',                'shaoxing-wine',                'Pantry',  false),
  ('doubanjiang',                  'doubanjiang',                  'Pantry',  false),
  ('fermented black beans',        'fermented-black-beans',        'Pantry',  false),
  ('chili oil',                    'chili-oil',                    'Pantry',  false),
  ('chinese sesame paste',         'chinese-sesame-paste',         'Pantry',  false),
  ('sweet chili sauce',            'sweet-chili-sauce',            'Pantry',  false),
  ('banana ketchup',               'banana-ketchup',               'Pantry',  false),
  ('nam prik pao',                 'nam-prik-pao',                 'Pantry',  false),
  ('massaman curry paste',         'massaman-curry-paste',         'Pantry',  false),
  ('tamarind paste',               'tamarind-paste',               'Pantry',  false),
  ('aji amarillo paste',           'aji-amarillo-paste',           'Pantry',  false),
  ('achiote paste',                'achiote-paste',                'Pantry',  false),
  ('chipotle in adobo',            'chipotle-in-adobo',            'Pantry',  false),
  ('piloncillo',                   'piloncillo',                   'Pantry',  false),
  ('palm sugar',                   'palm-sugar',                   'Pantry',  false),
  ('jaggery',                      'jaggery',                      'Pantry',  false),
  ('pomegranate molasses',         'pomegranate-molasses',         'Pantry',  false),
  ('preserved lemon',              'preserved-lemon',              'Pantry',  false),
  ('red palm oil',                 'red-palm-oil',                 'Pantry',  false),
  ('coconut water',                'coconut-water',                'Pantry',  false),
  ('black olives',                 'black-olives',                 'Pantry',  false),
  -- Pantry: grains, legumes, noodles, starches
  ('short-grain rice',             'short-grain-rice',             'Pantry',  false),
  ('glutinous rice',               'glutinous-rice',               'Pantry',  false),
  ('flattened rice',               'flattened-rice',               'Pantry',  false),
  ('korean rice cakes',            'korean-rice-cakes',            'Pantry',  false),
  ('sweet potato starch noodles',  'sweet-potato-starch-noodles',  'Pantry',  false),
  ('yakisoba noodles',             'yakisoba-noodles',             'Pantry',  false),
  ('chinese wheat noodles',        'chinese-wheat-noodles',        'Pantry',  false),
  ('toor dal',                     'toor-dal',                     'Pantry',  false),
  ('chana dal',                    'chana-dal',                    'Pantry',  false),
  ('urad dal',                     'urad-dal',                     'Pantry',  false),
  ('chickpea flour',               'chickpea-flour',               'Pantry',  false),
  ('potato starch',                'potato-starch',                'Pantry',  false),
  ('pigeon peas',                  'pigeon-peas',                  'Pantry',  false),
  ('gigante beans',                'gigante-beans',                'Pantry',  false),
  ('fava beans',                   'fava-beans',                   'Pantry',  false),
  -- Other: wrappers and shells
  ('spring roll wrappers',         'spring-roll-wrappers',         'Other',   false),
  ('tostadas',                     'tostadas',                     'Other',   false),
  -- Spices
  ('gochugaru',                    'gochugaru',                    'Spices',  false),
  ('berbere',                      'berbere',                      'Spices',  false),
  ('asafoetida',                   'asafoetida',                   'Spices',  false),
  ('dried mango powder',           'dried-mango-powder',           'Spices',  false),
  ('dried fenugreek leaves',       'dried-fenugreek-leaves',       'Spices',  false),
  ('pav bhaji masala',             'pav-bhaji-masala',             'Spices',  false),
  ('sambar powder',                'sambar-powder',                'Spices',  false),
  ('red chili powder',             'red-chili-powder',             'Spices',  false),
  ('cumin seeds',                  'cumin-seeds',                  'Spices',  false),
  ('coriander seeds',              'coriander-seeds',              'Spices',  false),
  ('fenugreek seeds',              'fenugreek-seeds',              'Spices',  false),
  ('black peppercorns',            'black-peppercorns',            'Spices',  true),
  ('sichuan peppercorns',          'sichuan-peppercorns',          'Spices',  false),
  ('whole cloves',                 'whole-cloves',                 'Spices',  false),
  ('allspice berries',             'allspice-berries',             'Spices',  false),
  ('aleppo pepper',                'aleppo-pepper',                'Spices',  false),
  ('dried mint',                   'dried-mint',                   'Spices',  false),
  ('dried red chiles',             'dried-red-chiles',             'Spices',  false),
  ('guajillo chile',               'guajillo-chile',               'Spices',  false),
  ('pasilla chile',                'pasilla-chile',                'Spices',  false),
  ('chile de arbol',               'chile-de-arbol',               'Spices',  false)
on conflict (canonical_name) do update
  set aisle_category   = excluded.aisle_category,
      is_pantry_staple = excluded.is_pantry_staple;

-- ---------------------------------------------------------------------------
-- Aliases
--
-- Four kinds of row here, and only four -- anything else is noise:
--
--   1. REGIONAL synonyms      aubergine -> eggplant, coriander -> cilantro
--   2. USDA phrasings         "peppers, sweet, red" -> red bell pepper
--   3. SHORTHAND a cook types  evoo -> olive oil, half and half
--   4. IRREGULAR plurals      leaves, loaves -- regular ones are handled by
--                             singularize_ingredient_name() and would be dead rows
--
-- Simple plurals are deliberately ABSENT. "tomatoes" -> "tomato" is done by the
-- resolver; adding it here would be 400 rows of maintenance that hide the real
-- synonyms in the noise.
--
-- An alias must not repeat a canonical_name: the resolver checks canonical names
-- first, so such a row can never win, and it reads as a claim that is never true.
-- ---------------------------------------------------------------------------
-- Staged in a temp table first so the seed can CHECK itself before it writes.
-- Inserting straight from a VALUES list joined to ingredients means a typo in a
-- canonical name silently drops that alias: no error, no row, and a synonym
-- nobody notices is missing until the match rate is quietly wrong. That is the
-- exact failure mode this milestone exists to prevent, so it gets a guard.
create temp table _alias_seed (canonical citext, alias citext) on commit drop;

insert into _alias_seed (canonical, alias) values
  -- Alliums. The DoD case: all three of these must return one id.
  ('scallion',            'green onion'),
  ('scallion',            'spring onion'),
  ('scallion',            'salad onion'),
  ('scallion',            'onions, spring or scallions'),
  ('yellow onion',        'brown onion'),
  ('yellow onion',        'cooking onion'),
  ('yellow onion',        'onions, raw'),
  ('sweet onion',         'vidalia onion'),
  ('garlic',              'garlic clove'),
  ('garlic',              'cloves of garlic'),
  ('garlic',              'fresh garlic'),
  ('chives',              'fresh chives'),

  -- Regional synonyms -- the classic British/American splits.
  ('eggplant',            'aubergine'),
  ('zucchini',            'courgette'),
  ('arugula',             'rocket'),
  ('fresh cilantro',      'chinese parsley'),
  ('fresh cilantro',      'coriander leaves'),
  ('fresh cilantro',      'fresh coriander'),
  ('fresh cilantro',      'cilantro'),
  ('chickpeas',           'garbanzo beans'),
  ('chickpeas',           'garbanzo'),
  ('chickpeas',           'ceci beans'),
  ('crushed red pepper',  'red pepper flakes'),
  ('crushed red pepper',  'chili flakes'),
  ('crushed red pepper',  'chilli flakes'),
  ('crushed red pepper',  'pepper flakes'),
  ('green bell pepper',   'capsicum'),
  ('snap peas',           'sugar snap peas'),
  ('green beans',         'string beans'),
  ('green beans',         'french beans'),
  ('rutabaga',            'swede'),
  ('beet',                'beetroot'),
  ('corn',                'sweetcorn'),
  ('corn',                'corn on the cob'),
  ('cornstarch',          'corn flour'),
  ('cornstarch',          'cornflour'),
  ('heavy cream',         'double cream'),
  ('heavy cream',         'whipping cream'),
  ('heavy cream',         'heavy whipping cream'),
  ('powdered sugar',      'icing sugar'),
  ('powdered sugar',      'confectioners sugar'),
  ('granulated sugar',    'caster sugar'),
  ('granulated sugar',    'white sugar'),
  ('granulated sugar',    'sugar'),
  ('all-purpose flour',   'plain flour'),
  ('all-purpose flour',   'flour'),
  ('all-purpose flour',   'ap flour'),
  ('shrimp',              'prawns'),
  ('ground beef',         'beef mince'),
  ('ground beef',         'minced beef'),
  ('ground beef',         'hamburger meat'),
  ('crushed red pepper',  'crushed chillies'),

  -- USDA FoodData Central phrasing. These are how the source names things;
  -- keeping them here is what lets the M1.5.4 nutrition pipeline join cleanly.
  ('red bell pepper',     'peppers, sweet, red'),
  ('red bell pepper',     'sweet red pepper'),
  ('green bell pepper',   'peppers, sweet, green'),
  ('green bell pepper',   'sweet green pepper'),
  ('carrot',              'carrots, raw'),
  ('celery',              'celery, raw'),
  ('spinach',             'spinach, raw'),
  ('russet potato',       'potatoes, russet'),
  ('russet potato',       'baking potato'),
  ('sweet potato',        'sweet potatoes, raw'),
  ('sweet potato',        'yam'),
  ('tomato',              'tomatoes, red, ripe, raw'),
  ('tomato',              'fresh tomato'),
  ('chicken breast',      'chicken, broilers or fryers, breast'),
  ('chicken breast',      'boneless skinless chicken breast'),
  ('chicken breast',      'chicken breasts, boneless'),
  ('chicken thighs',      'boneless skinless chicken thighs'),
  ('chicken thighs',      'chicken thigh'),
  ('ground beef',         'beef, ground, 85% lean'),
  ('ground turkey',       'turkey, ground'),
  ('milk',                'milk, reduced fat, fluid, 2% milkfat'),
  ('milk',                'whole milk'),
  ('milk',                'skim milk'),
  ('milk',                '2% milk'),
  ('milk',                'low-fat milk'),
  ('milk',                'nonfat milk'),
  ('milk',                'fat free milk'),
  ('chicken broth',       'low-sodium chicken broth'),
  ('chicken broth',       'reduced sodium chicken broth'),
  ('beef broth',          'low-sodium beef broth'),
  ('vegetable broth',     'low-sodium vegetable broth'),
  ('spinach',             'fresh spinach'),
  ('saffron',             'saffron threads'),
  ('greek yogurt',        'plain nonfat greek yogurt'),
  ('greek yogurt',        'nonfat greek yogurt'),
  ('egg',                 'egg, whole, raw, fresh'),
  ('egg',                 'large egg'),
  ('egg',                 'large eggs'),
  ('rolled oats',         'oats, old fashioned'),
  ('rolled oats',         'old-fashioned oats'),
  ('rolled oats',         'oatmeal'),
  ('rolled oats',         'oats'),
  ('black beans',         'beans, black, mature seeds'),
  ('kidney beans',        'beans, kidney, red, mature seeds'),
  ('brown rice',          'rice, brown, long-grain'),
  ('white rice',          'rice, white, long-grain'),
  ('white rice',          'long grain rice'),
  ('vegetable oil',       'oil, vegetable'),
  ('vegetable oil',       'neutral oil'),
  ('vegetable oil',       'cooking oil'),
  ('vegetable oil',       'oil'),

  -- Shorthand and brand-generic forms a cook actually types.
  ('olive oil',           'evoo'),
  ('olive oil',           'extra virgin olive oil'),
  ('olive oil',           'extra-virgin olive oil'),
  ('toasted sesame oil',  'sesame oil'),
  ('half-and-half',       'half and half'),
  ('parmesan',            'parmigiano reggiano'),
  ('parmesan',            'parmigiano-reggiano'),
  ('parmesan',            'parmesan cheese'),
  ('parmesan',            'grated parmesan'),
  ('pecorino romano',     'pecorino'),
  ('pecorino romano',     'romano cheese'),
  ('mozzarella',          'mozzarella cheese'),
  ('mozzarella',          'shredded mozzarella'),
  ('cheddar cheese',      'cheddar'),
  ('cheddar cheese',      'sharp cheddar'),
  ('cheddar cheese',      'shredded cheddar'),
  ('gruyere',             'gruyère'),
  ('feta',                'feta cheese'),
  ('goat cheese',         'chevre'),
  ('cream cheese',        'philadelphia'),
  ('greek yogurt',        'plain greek yogurt'),
  ('plain yogurt',        'yogurt'),
  ('plain yogurt',        'yoghurt'),
  ('sour cream',          'soured cream'),
  ('unsalted butter',     'sweet butter'),
  ('butter',              'salted butter'),
  ('white miso',          'miso'),
  ('white miso',          'miso paste'),
  ('white miso',          'shiro miso'),
  ('harissa paste',       'harissa'),
  ('gochujang',           'korean chili paste'),
  ('gochujang',           'korean red pepper paste'),
  ('sriracha',            'rooster sauce'),
  ('soy sauce',           'shoyu'),
  ('soy sauce',           'light soy sauce'),
  ('tamari',              'gluten free soy sauce'),
  ('fish sauce',          'nuoc mam'),
  ('fish sauce',          'nam pla'),
  ('dijon mustard',       'dijon'),
  ('yellow mustard',      'mustard'),
  ('barbecue sauce',      'bbq sauce'),
  ('mayonnaise',          'mayo'),
  ('ketchup',             'tomato ketchup'),
  ('worcestershire sauce','worcester sauce'),
  ('breadcrumbs',         'bread crumbs'),
  ('breadcrumbs',         'dried breadcrumbs'),
  ('panko breadcrumbs',   'panko'),
  ('coconut milk',        'full fat coconut milk'),
  ('coconut milk',        'canned coconut milk'),
  ('chicken broth',       'chicken stock'),
  ('beef broth',          'beef stock'),
  ('vegetable broth',     'vegetable stock'),
  ('vegetable broth',     'veggie broth'),
  ('crushed tomatoes',    'canned crushed tomatoes'),
  ('whole tomatoes',      'canned whole tomatoes'),
  ('whole tomatoes',      'san marzano tomatoes'),
  ('diced tomatoes',      'canned diced tomatoes'),
  ('tomato paste',        'concentrated tomato puree'),
  ('sun-dried tomatoes',  'sundried tomatoes'),
  ('canned tuna',         'tuna, canned in water'),
  ('canned tuna',         'tinned tuna'),
  ('anchovies',           'anchovy fillets'),
  ('firm tofu',           'tofu'),
  ('firm tofu',           'extra firm tofu'),
  ('silken tofu',         'soft tofu'),
  ('edamame',             'soybeans, green'),

  -- Herbs: the bare word, assigned per the fresh/dried rule above.
  ('fresh parsley',       'parsley'),
  ('fresh parsley',       'flat-leaf parsley'),
  ('fresh parsley',       'italian parsley'),
  ('fresh basil',         'basil'),
  ('fresh mint',          'mint'),
  ('fresh dill',          'dill'),
  ('fresh dill',          'dill weed'),
  ('fresh tarragon',      'tarragon'),
  ('dried oregano',       'oregano'),
  ('dried thyme',         'thyme'),
  ('dried rosemary',      'rosemary'),
  ('dried sage',          'sage'),
  ('bay leaf',            'bay leaves'),
  ('bay leaf',            'dried bay leaf'),

  -- Spices. "coriander" bare means the seed in US recipes; the leaf is
  -- "fresh coriander", which is mapped to cilantro above.
  ('ground coriander',    'coriander'),
  ('ground cumin',        'cumin'),
  ('ground cinnamon',     'cinnamon'),
  ('ground turmeric',     'turmeric'),
  ('ground ginger',       'dried ginger'),
  ('ground nutmeg',       'nutmeg'),
  ('ground allspice',     'allspice'),
  ('ground cloves',       'cloves'),
  ('cayenne',             'cayenne pepper'),
  ('cayenne',             'ground cayenne'),
  ('black pepper',        'pepper'),
  ('black pepper',        'freshly ground black pepper'),
  ('black pepper',        'ground black pepper'),
  ('salt',                'table salt'),
  ('salt',                'fine sea salt'),
  ('kosher salt',         'coarse salt'),
  ('kosher salt',         'flaky salt'),
  ('kosher salt',         'sea salt'),
  ('paprika',             'sweet paprika'),
  ('chili powder',        'chilli powder'),
  ('old bay seasoning',   'old bay'),
  ('za''atar',            'zaatar'),
  ('chinese five spice',  'five spice powder'),

  -- Produce shorthand and irregular plurals.
  ('mushrooms',           'button mushrooms'),
  ('mushrooms',           'white mushrooms'),
  ('mushrooms',           'mixed mushrooms'),
  ('cremini mushrooms',   'baby bella mushrooms'),
  ('cremini mushrooms',   'chestnut mushrooms'),
  ('shiitake mushrooms',  'dried shiitake'),
  ('collard greens',      'collards'),
  ('swiss chard',         'chard'),
  ('brussels sprouts',    'brussel sprouts'),
  ('napa cabbage',        'chinese cabbage'),
  ('bok choy',            'pak choi'),
  ('bok choy',            'baby bok choy'),
  ('romaine lettuce',     'cos lettuce'),
  ('mixed greens',        'salad greens'),
  ('mixed greens',        'spring mix'),
  ('cherry tomato',       'grape tomatoes'),
  ('jalapeno',            'jalapeño'),
  ('jalapeno',            'jalapeno pepper'),
  ('poblano pepper',      'ancho chile'),
  ('lemon',               'lemon juice'),
  ('lemon',               'lemon zest'),
  ('lime',                'lime juice'),
  ('lime',                'lime zest'),
  -- NOTE: no 'orange juice' alias -- it is its own canonical ingredient.
  -- lemon juice and lime juice stay aliases on purpose: those appear in
  -- teaspoon quantities as acid, where the fruit is a fair substitute. Orange
  -- juice appears by the cup, where it is not.
  ('ginger',              'fresh ginger'),
  ('ginger',              'ginger root'),
  ('strawberries',        'strawberry'),
  ('blueberries',         'blueberry'),
  ('raspberries',         'raspberry'),
  ('blackberries',        'blackberry'),
  ('cherries',            'cherry'),
  ('grapes',              'grape'),
  ('dried cranberries',   'craisins'),
  ('shredded coconut',    'desiccated coconut'),

  -- Pasta, grains and bread.
  ('spaghetti',           'tonnarelli'),
  ('spaghetti',           'spaghetti noodles'),
  ('macaroni',            'elbow macaroni'),
  ('macaroni',            'elbows'),
  ('angel hair',          'capellini'),
  ('egg noodles',         'wide egg noodles'),
  ('rice noodles',        'rice vermicelli'),
  ('rice noodles',        'pad thai noodles'),
  ('ramen noodles',       'instant ramen'),
  ('couscous',            'israeli couscous'),
  ('bulgur',              'cracked wheat'),
  ('corn tortillas',      'corn tortilla'),
  ('flour tortillas',     'flour tortilla'),
  ('flour tortillas',     'tortillas'),
  ('sandwich bread',      'white bread'),
  ('sandwich bread',      'bread'),
  ('baguette',            'french bread'),
  ('pita bread',          'pita'),
  ('hamburger buns',      'burger buns'),
  ('cooking spray',       'nonstick cooking spray'),
  ('active dry yeast',    'instant yeast'),
  ('active dry yeast',    'yeast'),
  ('semisweet chocolate', 'dark chocolate'),
  ('cocoa powder',        'unsweetened cocoa powder'),
  ('maple syrup',         'pure maple syrup'),
  ('peanut butter',       'creamy peanut butter'),
  ('dry white wine',      'white wine'),
  ('dry red wine',        'red wine'),
  ('hot dogs',            'frankfurters'),
  ('italian sausage',     'sweet italian sausage'),
  ('bacon',               'streaky bacon'),
  ('chuck roast',         'beef chuck'),
  ('pork shoulder',       'pork butt'),
  ('pork shoulder',       'boston butt'),
  ('rotisserie chicken',  'cooked chicken'),
  ('rotisserie chicken',  'shredded chicken'),

  -- From the USDA MyPlate unresolved queue (M1.5.3). These are the ones
  -- modifier stripping alone cannot reach, because the remaining words are not
  -- the canonical name either.
  ('corn',                'sweet corn'),
  ('corn',                'whole kernel corn'),
  ('corn',                'corn kernels'),
  ('green bell pepper',   'green pepper'),
  ('red bell pepper',     'red pepper'),
  ('rolled oats',         'quick cooking oats'),
  ('rolled oats',         'quick oats'),
  ('rolled oats',         'oatmeal'),
  ('apple',               'granny smith apple'),
  ('apple',               'tart apples'),
  ('apple',               'cooking apples'),
  ('chuck roast',         'beef chuck roast'),
  ('chuck roast',         'beef roast'),
  ('ground beef',         'hamburger meat'),
  ('cod',                 'fish fillets'),
  ('tilapia',             'tilapia fish'),
  ('margarine',           'oleo'),
  ('applesauce',          'apple sauce'),
  ('dry milk powder',     'nonfat dry milk'),
  ('dry milk powder',     'powdered milk'),
  ('whipped topping',     'whipped cream topping'),
  ('green chiles',        'green chilies'),
  ('green chiles',        'diced green chilies'),
  ('mandarin orange',     'mandarin oranges'),
  ('salad dressing',      'mayonnaise-type dressing'),
  ('vinaigrette',         'vinaigrette dressing'),
  ('graham crackers',     'graham cracker crumbs'),
  ('mixed vegetables',    'frozen mixed vegetables'),
  ('shredded coconut',    'flaked coconut'),
  ('pork shoulder',       'lean pork'),
  ('grapes',              'seedless grapes'),
  ('couscous',            'whole wheat couscous'),
  ('pineapple',           'pineapple chunks'),
  ('beet',                'whole beets'),
  ('peanuts',             'dry roasted peanuts'),
  ('vanilla yogurt',      'low fat vanilla yogurt'),
  ('chicken bouillon',    'chicken bouillon granules'),
  ('chicken bouillon',    'chicken bouillon cube'),
  ('beef bouillon',       'beef bouillon granules'),
  ('cream of mushroom soup','condensed cream of mushroom soup'),
  ('cream of chicken soup', 'condensed cream of chicken soup'),
  ('peas',                'frozen peas'),
  ('peas',                'green peas'),
  ('peas',                'sweet peas'),
  ('corn',                'cream style corn'),
  ('sandwich bread',      'whole wheat bread'),
  ('sandwich bread',      'wheat bread'),
  ('egg substitute',      'liquid egg substitute'),
  ('egg substitute',      'dry egg mix'),
  ('coffee',              'brewed coffee'),
  ('coffee',              'instant coffee'),
  ('maple syrup',         'pancake syrup'),
  ('mixed greens',        'mesclun'),
  ('mixed greens',        'baby greens'),
  ('cheddar cheese',      'colby jack cheese'),
  ('monterey jack',       'colby monterey jack cheese'),
  ('water',               'boiling water'),
  ('water',               'cold water'),
  ('water',               'warm water'),
  ('water',               'ice water'),
  ('water',               'ice cubes'),
  ('orange',              'orange peel'),
  ('orange',              'orange zest'),
  ('barley',              'pearl barley'),
  ('chicken bouillon',    'bouillon'),
  ('chicken bouillon',    'bouillon cubes'),

  -- Second pass aliases, same source: the full-corpus rejection queue.
  ('pasta',               'pasta shells'),
  ('pasta',               'whole wheat pasta'),
  ('pasta',               'noodles'),
  ('chicken',             'chicken pieces'),
  ('chicken',             'chicken parts'),
  ('white beans',         'great northern white beans'),
  ('water',               'ice'),
  ('kiwi',                'kiwifruit'),
  ('kiwi',                'kiwi fruit'),
  ('canned tuna',         'water packed tuna'),
  ('canned tuna',         'light tuna'),
  ('canned tuna',         'chunk light tuna'),
  ('flour tortillas',     'whole wheat tortilla'),
  ('flour tortillas',     'tortilla'),
  ('pita bread',          'pita pockets'),
  ('pita bread',          'whole wheat pita'),
  ('flaxseed',            'flax seeds'),
  ('orange juice',        'orange juice concentrate'),
  ('dried sage',          'ground sage'),
  ('ricotta',             'ricotta cheese'),
  ('blue cheese',         'gorgonzola cheese'),
  ('blue cheese',         'gorgonzola'),
  ('italian seasoning',   'italian herbs'),
  ('italian seasoning',   'italian herb mix'),
  ('italian seasoning',   'italian herb blend'),
  ('active dry yeast',    'rapid rise yeast'),
  ('active dry yeast',    'dry yeast'),
  ('yellow mustard',      'spicy brown mustard'),
  ('yellow mustard',      'brown mustard'),
  ('spaghetti sauce',     'pasta sauce'),
  ('shredded cheese',     'cheese'),
  ('raisins',             'california raisins'),
  ('pear',                'danjou pears'),
  ('kale',                'italian kale'),
  ('walleye',             'walleye fillets'),
  ('salt',                'seasoned salt'),

  -- World-cuisine vocabulary (wave 1, content lane). Regional names and
  -- romanisations only; nothing here is a simple plural.
  ('daikon',                       'daikon radish'),
  ('daikon',                       'mooli'),
  ('daikon',                       'white radish'),
  ('bean sprouts',                 'mung bean sprouts'),
  ('bean sprouts',                 'beansprouts'),
  ('soybean sprouts',              'soy bean sprouts'),
  ('soybean sprouts',              'kongnamul'),
  ('curry leaves',                 'fresh curry leaves'),
  ('curry leaves',                 'curry leaf'),
  ('galangal',                     'thai ginger'),
  ('galangal',                     'blue ginger'),
  ('kaffir lime leaves',           'makrut lime leaves'),
  ('kaffir lime leaves',           'lime leaves'),
  ('thai basil',                   'horapa'),
  ('thai basil',                   'asian basil'),
  ('holy basil',                   'thai holy basil'),
  ('holy basil',                   'gaprao'),
  ('holy basil',                   'tulsi'),
  ('green papaya',                 'unripe papaya'),
  ('long beans',                   'yardlong beans'),
  ('long beans',                   'yard-long beans'),
  ('long beans',                   'snake beans'),
  ('thai eggplant',                'thai round eggplant'),
  ('water spinach',                'kangkong'),
  ('water spinach',                'ong choy'),
  ('water spinach',                'morning glory'),
  ('scotch bonnet',                'scotch bonnet pepper'),
  ('scotch bonnet',                'scotch bonnet chile'),
  ('green plantain',               'unripe plantain'),
  ('ripe plantain',                'yellow plantain'),
  ('ripe plantain',                'sweet plantain'),
  ('paneer',                       'indian cottage cheese'),
  ('mexican crema',                'crema'),
  ('mexican crema',                'crema mexicana'),
  ('pork belly',                   'pork belly slices'),
  ('fish cakes',                   'eomuk'),
  ('fish cakes',                   'odeng'),
  ('dried shrimp',                 'dried prawns'),
  ('liver pate',                   'pate'),
  ('liver pate',                   'chicken liver pate'),
  ('dashi',                        'dashi stock'),
  ('dashi',                        'dashi granules'),
  ('dashi',                        'hondashi'),
  ('bonito flakes',                'katsuobushi'),
  ('bonito flakes',                'dried bonito flakes'),
  ('kombu',                        'dried kelp'),
  ('kombu',                        'dashima'),
  ('wakame',                       'dried wakame'),
  ('aonori',                       'ao nori'),
  ('aonori',                       'green seaweed flakes'),
  ('pickled ginger',               'beni shoga'),
  ('pickled ginger',               'sushi ginger'),
  ('pickled ginger',               'red pickled ginger'),
  ('japanese curry roux',          'curry roux'),
  ('japanese curry roux',          'golden curry'),
  ('black vinegar',                'chinkiang vinegar'),
  ('black vinegar',                'chinkiang black vinegar'),
  ('black vinegar',                'zhenjiang vinegar'),
  ('cane vinegar',                 'sukang maasim'),
  ('cane vinegar',                 'sugarcane vinegar'),
  ('shaoxing wine',                'shaoxing rice wine'),
  ('shaoxing wine',                'chinese cooking wine'),
  ('shaoxing wine',                'shaoxing'),
  ('doubanjiang',                  'chili bean paste'),
  ('doubanjiang',                  'pixian doubanjiang'),
  ('doubanjiang',                  'broad bean chili paste'),
  ('fermented black beans',        'douchi'),
  ('fermented black beans',        'salted black beans'),
  ('chinese sesame paste',         'sesame paste'),
  ('chili oil',                    'chile oil'),
  ('chili oil',                    'sichuan chili oil'),
  ('sweet chili sauce',            'thai sweet chili sauce'),
  ('banana ketchup',               'banana sauce'),
  ('nam prik pao',                 'thai roasted chili paste'),
  ('nam prik pao',                 'roasted chili paste'),
  ('massaman curry paste',         'massaman paste'),
  ('tamarind paste',               'tamarind'),
  ('tamarind paste',               'tamarind concentrate'),
  ('aji amarillo paste',           'aji amarillo'),
  ('aji amarillo paste',           'yellow chili paste'),
  ('achiote paste',                'annatto paste'),
  ('achiote paste',                'recado rojo'),
  ('chipotle in adobo',            'chipotle peppers in adobo'),
  ('chipotle in adobo',            'chipotles in adobo'),
  ('chipotle in adobo',            'canned chipotle'),
  ('piloncillo',                   'panela'),
  ('piloncillo',                   'mexican brown sugar'),
  ('palm sugar',                   'coconut palm sugar'),
  ('pomegranate molasses',         'pomegranate syrup'),
  ('preserved lemon',              'salt-preserved lemon'),
  ('red palm oil',                 'palm oil'),
  ('black olives',                 'ripe olives'),
  ('black olives',                 'canned black olives'),
  ('short-grain rice',             'sushi rice'),
  ('short-grain rice',             'japanese rice'),
  ('short-grain rice',             'calrose rice'),
  ('glutinous rice',               'sweet rice'),
  ('glutinous rice',               'sticky rice'),
  ('glutinous rice',               'malagkit'),
  ('flattened rice',               'poha'),
  ('flattened rice',               'pohe'),
  ('flattened rice',               'beaten rice'),
  ('flattened rice',               'rice flakes'),
  ('korean rice cakes',            'tteok'),
  ('korean rice cakes',            'garaetteok'),
  ('korean rice cakes',            'tteokbokki rice cakes'),
  ('sweet potato starch noodles',  'dangmyeon'),
  ('sweet potato starch noodles',  'korean glass noodles'),
  ('sweet potato starch noodles',  'korean sweet potato noodles'),
  ('chinese wheat noodles',        'fresh wheat noodles'),
  ('chinese wheat noodles',        'lamian noodles'),
  ('toor dal',                     'toovar dal'),
  ('toor dal',                     'arhar dal'),
  ('toor dal',                     'split pigeon peas'),
  ('chana dal',                    'split chickpeas'),
  ('chana dal',                    'bengal gram'),
  ('urad dal',                     'split black gram'),
  ('urad dal',                     'black gram dal'),
  ('chickpea flour',               'besan'),
  ('chickpea flour',               'gram flour'),
  ('potato starch',                'katakuriko'),
  ('pigeon peas',                  'gandules'),
  ('pigeon peas',                  'gungo peas'),
  ('gigante beans',                'gigantes'),
  ('gigante beans',                'giant white beans'),
  ('gigante beans',                'elephant beans'),
  ('fava beans',                   'broad beans'),
  ('fava beans',                   'canned fava beans'),
  ('spring roll wrappers',         'lumpia wrappers'),
  ('spring roll wrappers',         'spring roll skins'),
  ('tostadas',                     'tostada shells'),
  ('gochugaru',                    'korean red pepper flakes'),
  ('gochugaru',                    'korean chili flakes'),
  ('gochugaru',                    'korean chile flakes'),
  ('berbere',                      'berbere spice'),
  ('berbere',                      'berbere seasoning'),
  ('asafoetida',                   'hing'),
  ('asafoetida',                   'asafetida'),
  ('dried mango powder',           'amchur'),
  ('dried mango powder',           'amchoor'),
  ('dried fenugreek leaves',       'kasuri methi'),
  ('dried fenugreek leaves',       'methi leaves'),
  ('sambar powder',                'sambar masala'),
  ('red chili powder',             'kashmiri chili powder'),
  ('red chili powder',             'indian chili powder'),
  ('red chili powder',             'red chilli powder'),
  ('cumin seeds',                  'whole cumin'),
  ('cumin seeds',                  'jeera'),
  ('coriander seeds',              'whole coriander seeds'),
  ('fenugreek seeds',              'methi seeds'),
  ('black peppercorns',            'peppercorns'),
  ('black peppercorns',            'whole peppercorns'),
  ('sichuan peppercorns',          'szechuan peppercorns'),
  ('sichuan peppercorns',          'sichuan pepper'),
  ('allspice berries',             'whole allspice'),
  ('allspice berries',             'pimento berries'),
  ('aleppo pepper',                'pul biber'),
  ('aleppo pepper',                'aleppo chile flakes'),
  ('dried red chiles',             'dried red chilies'),
  ('dried red chiles',             'dried chili peppers'),
  ('dried red chiles',             'whole dried red chiles'),
  ('guajillo chile',               'dried guajillo chiles'),
  ('guajillo chile',               'guajillo'),
  ('pasilla chile',                'pasilla'),
  ('chile de arbol',               'arbol chile'),
  ('chile de arbol',               'chiles de arbol'),
  ('cardamom',                     'ground cardamom'),
  ('cardamom',                     'cardamom pod'),
  ('cardamom',                     'cardamom pods'),
  ('cardamom',                     'green cardamom')
;

do $guard$
declare
  orphans   text;
  shadowed  text;
begin
  -- An alias naming a canonical ingredient that does not exist.
  select string_agg(distinct s.canonical::text, ', ' order by s.canonical::text)
    into orphans
  from _alias_seed s
  left join ingredients i on i.canonical_name = s.canonical
  where i.id is null;

  if orphans is not null then
    raise exception 'alias seed references unknown canonical ingredients: %', orphans;
  end if;

  -- An alias that repeats a canonical_name. resolve_ingredient() checks
  -- canonical names first, so such a row can never win -- it is a dead claim.
  select string_agg(distinct s.alias::text, ', ' order by s.alias::text)
    into shadowed
  from _alias_seed s
  join ingredients i on i.canonical_name = s.alias;

  if shadowed is not null then
    raise exception 'alias rows shadow a canonical_name and can never match: %', shadowed;
  end if;
end
$guard$;

insert into ingredient_aliases (ingredient_id, alias)
select i.id, s.alias
from _alias_seed s
join ingredients i on i.canonical_name = s.canonical
on conflict (alias) do nothing;

commit;
