-- Generated by scripts/nutrition/nutrition.py --emit-mapping (M1.5.4). Idempotent.
-- Source of truth: scripts/nutrition/ingredient-map.json. Writes the USDA FoodData
-- Central id (and a curated density where one was needed) onto canonical ingredients.
begin;
update ingredients set fdc_id = 170931 where canonical_name = 'black pepper';
update ingredients set fdc_id = 169986 where canonical_name = 'cauliflower';
update ingredients set fdc_id = 170932 where canonical_name = 'cayenne';
update ingredients set fdc_id = 173800 where canonical_name = 'chickpeas';
update ingredients set fdc_id = 170501 where canonical_name = 'crushed tomatoes';
update ingredients set fdc_id = 171287 where canonical_name = 'egg';
update ingredients set fdc_id = 2525305, density_g_per_ml = 0.5 where canonical_name = 'garam masala';
update ingredients set fdc_id = 169230 where canonical_name = 'garlic';
update ingredients set fdc_id = 169231, density_g_per_ml = 0.4 where canonical_name = 'ginger';
update ingredients set fdc_id = 2244609, density_g_per_ml = 1.2 where canonical_name = 'gochujang';
update ingredients set fdc_id = 170922 where canonical_name = 'ground coriander';
update ingredients set fdc_id = 170923, density_g_per_ml = 0.42 where canonical_name = 'ground cumin';
update ingredients set fdc_id = 2546030, density_g_per_ml = 1.1 where canonical_name = 'harissa paste';
update ingredients set fdc_id = 169640 where canonical_name = 'honey';
update ingredients set fdc_id = 167746 where canonical_name = 'lemon';
update ingredients set fdc_id = 169251 where canonical_name = 'mushrooms';
update ingredients set fdc_id = 171413 where canonical_name = 'olive oil';
update ingredients set fdc_id = 171249 where canonical_name = 'pecorino romano';
update ingredients set fdc_id = 169727 where canonical_name = 'ramen noodles';
update ingredients set fdc_id = 170108 where canonical_name = 'red bell pepper';
update ingredients set fdc_id = 175167 where canonical_name = 'salmon';
update ingredients set fdc_id = 170005 where canonical_name = 'scallion';
update ingredients set fdc_id = 170151, density_g_per_ml = 0.6 where canonical_name = 'sesame seeds';
update ingredients set fdc_id = 171329 where canonical_name = 'smoked paprika';
update ingredients set fdc_id = 174277 where canonical_name = 'soy sauce';
update ingredients set fdc_id = 169736 where canonical_name = 'spaghetti';
update ingredients set fdc_id = 171016 where canonical_name = 'toasted sesame oil';
update ingredients set fdc_id = 172442 where canonical_name = 'white miso';
update ingredients set fdc_id = 170051 where canonical_name = 'whole tomatoes';
update ingredients set fdc_id = 170000 where canonical_name = 'yellow onion';
do $$ begin
  if (select count(*) from ingredients where fdc_id is not null and canonical_name in ('black pepper', 'cauliflower', 'cayenne', 'chickpeas', 'crushed tomatoes', 'egg', 'garam masala', 'garlic', 'ginger', 'gochujang', 'ground coriander', 'ground cumin', 'harissa paste', 'honey', 'lemon', 'mushrooms', 'olive oil', 'pecorino romano', 'ramen noodles', 'red bell pepper', 'salmon', 'scallion', 'sesame seeds', 'smoked paprika', 'soy sauce', 'spaghetti', 'toasted sesame oil', 'white miso', 'whole tomatoes', 'yellow onion')) <> 30 then
    raise exception 'seed-nutrition-fdc: some mapped ingredients are missing from ingredients';
  end if;
end $$;
commit;
