-- Generated by scripts/nutrition/nutrition.py (M1.5.4). Idempotent: safe to re-run.
-- Per-serving nutrition computed from USDA FoodData Central. The WHERE clause
-- refuses USDA MyPlate rows, which already carry USDA's own numbers.
begin;
update recipes set calories = 532, protein_g = 26, carbs_g = 77.6, fat_g = 12.4, sodium_mg = 580, fiber_g = 3.8 where slug = 'cacio-e-pepe' and source_name not ilike '%myplate%';
update recipes set calories = 223, protein_g = 10.9, carbs_g = 39.2, fat_g = 4, sodium_mg = 509, fiber_g = 10.5 where slug = 'chana-masala' and source_name not ilike '%myplate%';
update recipes set calories = 425, protein_g = 35.8, carbs_g = 10.8, fat_g = 25.9, sodium_mg = 407, fiber_g = 0.5 where slug = 'gochujang-glazed-salmon' and source_name not ilike '%myplate%';
update recipes set calories = 222, protein_g = 7.3, carbs_g = 23.8, fat_g = 12.3, sodium_mg = 240, fiber_g = 7.4 where slug = 'harissa-roast-cauliflower' and source_name not ilike '%myplate%';
update recipes set calories = 470, protein_g = 25.9, carbs_g = 71.7, fat_g = 9.2, sodium_mg = 1499, fiber_g = 2.5 where slug = 'miso-mushroom-ramen' and source_name not ilike '%myplate%';
update recipes set calories = 191, protein_g = 13.6, carbs_g = 16.3, fat_g = 9, sodium_mg = 427, fiber_g = 6.8 where slug = 'shakshuka' and source_name not ilike '%myplate%';
commit;
