#!/usr/bin/env python3
"""Generate supabase/seed-photos.sql from manifest/photos.json.

    python scripts/photos/apply_manifest.py > supabase/seed-photos.sql
    psql "$URL" -v ON_ERROR_STOP=1 -f supabase/seed-photos.sql

Idempotent: upserts on recipe_id, so re-running after the manifest grows (e.g.
when the ~100 new originals get photos) only adds or refreshes rows.

Fails LOUDLY if any manifest slug has no matching recipe -- a photo row that
silently attaches to nothing is the "it didn't error" trap CLAUDE.md warns about.
Run it only AFTER the upload (scripts/photos/upload_photos.py) so the rows never
point at files that are not in the bucket yet.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import MANIFEST_DIR  # noqa: E402

COLS = ["slug", "storage_path", "thumb_path", "width", "height", "alt_text", "source",
        "license", "license_url", "credit", "attribution_url", "source_image_url"]


def row_for_sql(r: dict) -> dict:
    out = {k: r.get(k) for k in COLS}
    # credit: the author for Commons; the agency for USDA public-domain rows.
    if r["source"] == "usda_myplate":
        out["credit"] = r.get("credit") or "USDA MyPlate Kitchen (U.S. Department of Agriculture)"
    return out


def main() -> None:
    rows = [row_for_sql(r) for r in json.loads((MANIFEST_DIR / "photos.json").read_text(encoding="utf-8"))]
    payload = json.dumps(rows, ensure_ascii=False)
    assert "$photos$" not in payload
    sys.stdout.reconfigure(encoding="utf-8", newline="\n")
    print(f"""-- GENERATED by scripts/photos/apply_manifest.py -- do not edit by hand.
-- {len(rows)} photo rows. Apply AFTER the files are uploaded to the `recipe-photos` bucket.
-- Idempotent (upsert on recipe_id).

begin;

create temp table _photo_src on commit drop as
select * from jsonb_to_recordset($photos${payload}$photos$::jsonb) as x(
  slug text, storage_path text, thumb_path text, width int, height int, alt_text text,
  source text, license text, license_url text, credit text, attribution_url text, source_image_url text);

-- Every manifest slug must match a recipe; fail loudly rather than skip silently.
do $$
declare missing text;
begin
  select string_agg(s.slug, ', ') into missing
  from _photo_src s left join recipes r on r.slug = s.slug where r.id is null;
  if missing is not null then
    raise exception 'manifest slugs with no recipe: %', missing;
  end if;
end $$;

insert into recipe_photos (recipe_id, storage_path, thumb_path, width, height, alt_text,
                           source, license, license_url, credit, attribution_url, source_image_url)
select r.id, s.storage_path, s.thumb_path, s.width, s.height, s.alt_text,
       s.source, s.license, s.license_url, s.credit, s.attribution_url, s.source_image_url
from _photo_src s join recipes r on r.slug = s.slug
on conflict (recipe_id) do update set
  storage_path = excluded.storage_path, thumb_path = excluded.thumb_path,
  width = excluded.width, height = excluded.height, alt_text = excluded.alt_text,
  source = excluded.source, license = excluded.license, license_url = excluded.license_url,
  credit = excluded.credit, attribution_url = excluded.attribution_url,
  source_image_url = excluded.source_image_url;

-- The old hot-links point at myplate-prod.azureedge.us, which is gone (every
-- one 404s). The photo now lives in recipe_photos; clear the dead column.
update recipes set image_url = null where image_url like 'https://myplate-prod.azureedge.us/%';

commit;
""")

if __name__ == "__main__":
    main()
